// import bcrypt from 'bcryptjs';
// import mongoose, { Schema, Document } from 'mongoose';
// import { v4 as uuidV4 } from 'uuid'

// export interface IUser extends Document {
//     _id: string;
//     id: string;
//     email: string;
//     name: string;
//     password: string;
//     role: 'agency' | 'agent' | 'admin';
//     createdAt: Date;
//     updatedAt: Date;
//     notifications: {
//         emailNotifications: boolean;
//         smsNotifications: boolean;
//     };
//     // -------------------------------------------Agency-specific fields---------------------------------------------------
//     agencyName?: string;
//     agencyType?: string;
//     profile?: {
//         photo?: string;
//         description?: string;
//         phone?: string;
//         telegramHandle?: string;
//         location?: {
//             country: string;
//             state: string;
//             zipcode: string;
//             addressLine: string;
//         };
//     };
//     licenses?: { type: string; number: string; expiryDate: Date }[];
//     billingInfo?: { enabled: boolean };
//     jobsPosted?: mongoose.Types.ObjectId[];
//     hiredAgents?: mongoose.Types.ObjectId[];
//     savedAgents?: mongoose.Types.ObjectId[];
//     //-------------------------------------------- Agent-specific --------------------------------------------------------
//     firstName?: string;
//     lastName?: string;
//     agentProfile?: {
//         photo?: string;
//         location?: {
//             country: string;
//             state: string;
//             zipcode: string;
//             addressLine: string;
//         };
//         autoGeneratedProfile?: string;
//         skills?: { name: string; details: string }[];
//         hourlyRate?: number;
//         licenses?: { type: string; number: string; expiryDate: Date }[];
//         trainingCertificates?: { name: string; date: Date }[];
//         taxForm?: string;
//         employmentHistory?: { company: string; role: string; startDate: Date; endDate?: Date }[];
//         education?: { institution: string; degree: string; startDate: Date; endDate?: Date }[];
//         additionalTraining?: { name: string; details: string }[];
//         stats?: {
//             visibility: 'Public' | 'Private' | 'BlitzOnly';
//             projectPreference?: string;
//             height?: number;
//             weight?: number;
//             experienceLevel: 'Beginner' | 'Intermediate' | 'Expert';
//             category: string;
//             expertise: string[];
//         };
//         availability?: { status: string; details: string };
//         languages?: { name: string; proficiency: 'Basic' | 'Intermediate' | 'Advanced' }[];
//         telegramHandle?: string;
//     };
//     paymentInfo?: { enabled: boolean };
//     appliedJobs?: mongoose.Types.ObjectId[];
//     activeJobs?: mongoose.Types.ObjectId[];
//     hiredJobs?: mongoose.Types.ObjectId[];
//     completedJobs?: mongoose.Types.ObjectId[];
//     savedJobs?: mongoose.Types.ObjectId[];
// }

// const UserSchema: Schema = new Schema(
//     {
//         id: { type: String, required: true, unique: true, default: uuidV4() },
//         email: { type: String, required: true, unique: true },
//         password: { type: String, required: true, minlength: 8 },
//         role: { type: String, enum: ['agency', 'agent', 'admin'], required: true },
//         notifications: {
//             emailNotifications: { type: Boolean, default: true },
//             smsNotifications: { type: Boolean, default: false },
//         },
//         //-------------------------------------------- Agency-specific fields--------------------------------------------
//         agencyName: {
//             type: String,
//             required: function (this: IUser) {
//                 return this.role === 'agency';
//             },
//             select: function (this: IUser) {
//                 return this.role === "agency"
//             }
//         },
//         agencyType: {
//             type: String,
//             required: function (this: IUser) {
//                 return this.role === 'agency';
//             },
//             select: function (this: IUser) {
//                 return this.role === "agency"
//             }
//         },
//         profile: {
//             photo: { type: String },
//             description: { type: String },
//             phone: {
//                 type: String,
//                 required: function (this: IUser) {
//                     return this.role === 'agency';
//                 },
//             },
//             telegramHandle: { type: String },
//             location: {
//                 country: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agency';
//                     },
//                 },
//                 state: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agency';
//                     },
//                     select: function (this: IUser) {
//                         return this.role === "agency"
//                     }
//                 },
//                 zipcode: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agency';
//                     },
//                     match: /^[0-9]{5,10}$/,
//                     select: function (this: IUser) {
//                         return this.role === "agency"
//                     }
//                 },
//                 addressLine: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agency';
//                     },
//                     select: function (this: IUser) {
//                         return this.role === "agency"
//                     }
//                 },
//             },
//         },
//         licenses: [
//             {
//                 type: { type: String, required: true },
//                 number: { type: String, required: true },
//                 expiryDate: { type: Date, required: true },
//             },
//         ],
//         billingInfo: {
//             enabled: { type: Boolean, default: false, },
//         },
//         jobsPosted: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
//         hiredAgents: [{ type: Schema.Types.ObjectId, ref: 'Agent' }],
//         savedAgents: [{ type: Schema.Types.ObjectId, ref: 'Agent' }],
//         // ---------------------------------------------Agent-specific fields------------------------------------------
//         firstName: {
//             type: String,
//             required: function (this: IUser) {
//                 return this.role === 'agent';
//             },
//         },
//         lastName: {
//             type: String,
//             required: function (this: IUser) {
//                 return this.role === 'agent';
//             },
//         },
//         agentProfile: {
//             photo: { type: String },
//             location: {
//                 country: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agent';
//                     },
//                 },
//                 state: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agent';
//                     },
//                 },
//                 zipcode: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agent';
//                     },
//                     match: /^[0-9]{5,10}$/,
//                 },
//                 addressLine: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agent';
//                     },
//                 },
//             },
//             autoGeneratedProfile: {
//                 type: String,
//                 required: function (this: IUser) {
//                     return this.role === 'agent';
//                 },
//             },
//             skills: [
//                 {
//                     name: { type: String, required: true },
//                     details: { type: String },
//                 },
//             ],
//             hourlyRate: {
//                 type: Number,
//                 required: function (this: IUser) {
//                     return this.role === 'agent';
//                 },
//                 min: 0,
//             },
//             licenses: [
//                 {
//                     type: { type: String, required: false },
//                     number: { type: String, required: false },
//                     expiryDate: { type: Date, required: false },
//                 },
//             ],
//             trainingCertificates: [
//                 {
//                     name: { type: String, required: false },
//                     date: { type: Date, required: false },
//                 },
//             ],
//             taxForm: { type: String },
//             employmentHistory: [
//                 {
//                     company: { type: String, required: false },
//                     role: { type: String, required: false },
//                     startDate: { type: Date, required: false },
//                     endDate: { type: Date },
//                 },
//             ],
//             education: [
//                 {
//                     institution: { type: String, required: false },
//                     degree: { type: String, required: false },
//                     startDate: { type: Date, required: false },
//                     endDate: { type: Date },
//                 },
//             ],
//             additionalTraining: [
//                 {
//                     name: { type: String, required: false },
//                     details: { type: String, required: false },
//                 },
//             ],
//             stats: {
//                 visibility: {
//                     type: String,
//                     enum: ['Public', 'Private', 'BlitzOnly'],
//                     required: function (this: IUser) {
//                         return this.role === 'agent';
//                     },
//                 },
//                 projectPreference: { type: String },
//                 height: { type: Number },
//                 weight: { type: Number },
//                 experienceLevel: {
//                     type: String,
//                     enum: ['Beginner', 'Intermediate', 'Expert'],
//                     required: function (this: IUser) {
//                         return this.role === 'agent';
//                     },
//                 },
//                 category: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agent';
//                     },
//                 },
//                 expertise: {
//                     type: [String],
//                     validate: [
//                         function (val: string[]) {
//                             return val.length <= 10;
//                         },
//                         'Expertise cannot exceed 10 items',
//                     ],
//                 },
//             },
//             availability: {
//                 status: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agent';
//                     },
//                 },
//                 details: {
//                     type: String,
//                     required: function (this: IUser) {
//                         return this.role === 'agent';
//                     },
//                 },
//             },
//             languages: [
//                 {
//                     name: { type: String, required: true },
//                     proficiency: { type: String, enum: ['Basic', 'Intermediate', 'Advanced'], required: true },
//                 },
//             ],
//             telegramHandle: { type: String },
//         },
//         paymentInfo: {
//             enabled: { type: Boolean, default: false },
//         },
//         appliedJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
//         activeJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
//         hiredJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
//         completedJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
//         savedJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
//     },
//     {
//         timestamps: true,
//         versionKey: false
//     }
// );

// // 🔐 Static method to hash a password
// UserSchema.statics.generateHash = async function (password: string): Promise<string> {
//     const saltRounds = 10;
//     return await bcrypt.hash(password, saltRounds);
// };

// // 🔐 Pre-save middleware to hash password
// UserSchema.pre<IUser>('save', async function (next) {
//     // Only hash the password if it's new or modified
//     if (!this.isModified('password')) return next();

//     try {
//         const saltRounds = 10;
//         this.password = await bcrypt.hash(this.password, saltRounds);
//         next();
//     } catch (err) {
//         next(err as any);
//     }
// });

// // 🔐 Instance method to compare password
// UserSchema.methods.comparePassword = async function (candidatePassword: string): Promise<boolean> {
//     return await bcrypt.compare(candidatePassword, this.password);
// };

// export const UserModel = mongoose.model<IUser>('User', UserSchema);



































import bcrypt from 'bcryptjs';
import mongoose, { Schema, Document, Types } from 'mongoose';
import { v4 as uuidV4 } from 'uuid';

// Interface for nested Location schema
export interface ILocation {
    country: string;
    state: string;
    zipcode: string;
    addressLine: string;
}

// Interface for nested License schema
export interface ILicense {
    type: string;
    number: string;
    expiryDate: Date;
}

// Interface for nested Skill schema
export interface ISkill {
    name: string;
    details?: string;
}

// Interface for nested TrainingCertificate schema
export interface ITrainingCertificate {
    name: string;
    date: Date;
}

// Interface for nested EmploymentHistory schema
export interface IEmploymentHistory {
    company: string;
    role: string;
    startDate: Date;
    endDate?: Date;
}

// Interface for nested Education schema
export interface IEducation {
    institution: string;
    degree: string;
    startDate: Date;
    endDate?: Date;
}

// Interface for nested AdditionalTraining schema
export interface IAdditionalTraining {
    name: string;
    details: string;
}

// Interface for nested Stats schema
export interface IStats {
    visibility: 'Public' | 'Private' | 'BlitzOnly';
    projectPreference?: string;
    height?: number;
    weight?: number;
    experienceLevel: 'Beginner' | 'Intermediate' | 'Expert';
    category: string;
    expertise: string[];
}

// Interface for nested Availability schema
export interface IAvailability {
    status: string;
    details: string;
}

// Interface for nested Language schema
export interface ILanguage {
    name: string;
    proficiency: 'Basic' | 'Intermediate' | 'Advanced';
}

// Interface for nested AgencyProfile schema
export interface IAgencyProfile {
    photo?: string;
    description?: string;
    phone: string;
    telegramHandle?: string;
    location: ILocation | Types.ObjectId;
}

// Interface for nested AgentProfile schema
export interface IAgentProfile {
    photo?: string;
    location: ILocation | Types.ObjectId;
    autoGeneratedProfile: string;
    skills: ISkill[];
    hourlyRate: number;
    licenses: ILicense[];
    trainingCertificates: ITrainingCertificate[];
    taxForm?: string;
    employmentHistory: IEmploymentHistory[];
    education: IEducation[];
    additionalTraining: IAdditionalTraining[];
    stats: IStats;// | Types.ObjectId;
    availability: IAvailability;// | Types.ObjectId;
    languages: ILanguage[];
    telegramHandle?: string;
}

// Main User interface
export interface IUser extends Document {
    _id: string;
    id: string;
    name: string;
    email: string;
    password: string;
    role: 'agency' | 'agent' | 'admin';
    createdAt: Date;
    updatedAt: Date;
    notifications: {
        emailNotifications: boolean;
        smsNotifications: boolean;
    };
    // Agency-specific fields
    agencyName?: string;
    agencyType?: string;
    profile?: IAgencyProfile | Types.ObjectId;
    licenses?: ILicense[];
    billingInfo?: { enabled: boolean };
    jobsPosted?: Types.ObjectId[];
    hiredAgents?: Types.ObjectId[];
    savedAgents?: Types.ObjectId[];
    // Agent-specific fields
    firstName?: string;
    lastName?: string;
    agentProfile?: IAgentProfile | Types.ObjectId;
    paymentInfo?: { enabled: boolean };
    appliedJobs?: Types.ObjectId[];
    activeJobs?: Types.ObjectId[];
    hiredJobs?: Types.ObjectId[];
    completedJobs?: Types.ObjectId[];
    savedJobs?: Types.ObjectId[];
    //generic--
    status: boolean,
    soft_delete: boolean,
    // Methods
    comparePassword(candidatePassword: string): Promise<boolean>;
}

// Location Schema
const LocationSchema: Schema<ILocation> = new Schema({
    country: {
        type: String,
        required: function (this: ILocation & { _parent?: IUser }) {
            return this._parent?.role === 'agency' || this._parent?.role === 'agent';
        },
    },
    state: {
        type: String,
        required: function (this: ILocation & { _parent?: IUser }) {
            return this._parent?.role === 'agency' || this._parent?.role === 'agent';
        },
    },
    zipcode: {
        type: String,
        required: function (this: ILocation & { _parent?: IUser }) {
            return this._parent?.role === 'agency' || this._parent?.role === 'agent';
        },
        match: /^[0-9]{5,10}$/,
    },
    addressLine: {
        type: String,
        required: function (this: ILocation & { _parent?: IUser }) {
            return this._parent?.role === 'agency' || this._parent?.role === 'agent';
        },
    },
});

// License Schema
const LicenseSchema: Schema<ILicense> = new Schema({
    type: { type: String, required: true },
    number: { type: String, required: true },
    expiryDate: { type: Date, required: true },
});

// Skill Schema
const SkillSchema: Schema<ISkill> = new Schema({
    name: { type: String, required: true },
    details: { type: String },
});

// TrainingCertificate Schema
const TrainingCertificateSchema: Schema<ITrainingCertificate> = new Schema({
    name: { type: String, required: false },
    date: { type: Date, required: false },
});

// EmploymentHistory Schema
const EmploymentHistorySchema: Schema<IEmploymentHistory> = new Schema({
    company: { type: String, required: false },
    role: { type: String, required: false },
    startDate: { type: Date, required: false },
    endDate: { type: Date },
});

// Education Schema
const EducationSchema: Schema<IEducation> = new Schema({
    institution: { type: String, required: false },
    degree: { type: String, required: false },
    startDate: { type: Date, required: false },
    endDate: { type: Date },
});

// AdditionalTraining Schema
const AdditionalTrainingSchema: Schema<IAdditionalTraining> = new Schema({
    name: { type: String, required: false },
    details: { type: String, required: false },
});

// Stats Schema
const StatsSchema: Schema<IStats> = new Schema({
    visibility: {
        type: String,
        enum: ['Public', 'Private', 'BlitzOnly'],
        required: function (this: IStats & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
    },
    projectPreference: { type: String },
    height: { type: Number },
    weight: { type: Number },
    experienceLevel: {
        type: String,
        enum: ['Beginner', 'Intermediate', 'Expert'],
        required: function (this: IStats & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
    },
    category: {
        type: String,
        required: function (this: IStats & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
    },
    expertise: {
        type: [String],
        validate: [
            function (val: string[]) {
                return val.length <= 10;
            },
            'Expertise cannot exceed 10 items',
        ],
    },
});

// Availability Schema
const AvailabilitySchema: Schema<IAvailability> = new Schema({
    status: {
        type: String,
        required: function (this: IAvailability & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
    },
    details: {
        type: String,
        required: function (this: IAvailability & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
    },
});

// Language Schema
const LanguageSchema: Schema<ILanguage> = new Schema({
    name: { type: String, required: true },
    proficiency: { type: String, enum: ['Basic', 'Intermediate', 'Advanced'], required: true },
});

// Agency Profile Schema
const AgencyProfileSchema: Schema<IAgencyProfile> = new Schema({
    photo: { type: String },
    description: { type: String },
    phone: {
        type: String,
        required: function (this: IAgencyProfile & { _parent?: IUser }) {
            return this._parent?.role === 'agency';
        },
    },
    telegramHandle: { type: String },
    location: { type: LocationSchema, required: true },
});

// Agent Profile Schema
const AgentProfileSchema: Schema<IAgentProfile> = new Schema({
    photo: { type: String },
    location: {
        type: LocationSchema,
        required: function (this: IAgentProfile & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
    },
    autoGeneratedProfile: {
        type: String,
        required: function (this: IAgentProfile & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
    },
    skills: [SkillSchema],
    hourlyRate: {
        type: Number,
        required: function (this: IAgentProfile & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
        min: 0,
    },
    licenses: [LicenseSchema],
    trainingCertificates: [TrainingCertificateSchema],
    taxForm: { type: String },
    employmentHistory: [EmploymentHistorySchema],
    education: [EducationSchema],
    additionalTraining: [AdditionalTrainingSchema],
    stats: {
        type: StatsSchema,
        required: function (this: IAgentProfile & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
    },
    availability: {
        type: AvailabilitySchema,
        required: function (this: IAgentProfile & { _parent?: IUser }) {
            return this._parent?.role === 'agent';
        },
    },
    languages: [LanguageSchema],
    telegramHandle: { type: String },
});

// Main User Schema
const UserSchema: Schema<IUser> = new Schema(
    {
        id: { type: String, required: true, unique: true, default: uuidV4 },
        email: { type: String, required: true, unique: true },
        password: { type: String, required: true, minlength: 8 },
        role: { type: String, enum: ['agency', 'agent', 'admin'], required: true },
        notifications: {
            emailNotifications: { type: Boolean, default: true },
            smsNotifications: { type: Boolean, default: false },
        },
        // -----------------------------------------------------------Agency-specific fields================---------------------
        agencyName: {
            type: String,
            required: function (this: IUser) {
                return this.role === 'agency';
            },
            // select: false,
            select: function (this: IUser) {
                return this.role === "agent" || this.role === "admin" ? false : true;
            },
        },
        agencyType: {
            type: String,
            required: function (this: IUser) {
                return this.role === 'agency';
            },
            // select: false,
            select: function (this: IUser) {
                return this.role === "agent" || this.role === "admin" ? false : true;
            },
        },
        profile: {
            type: AgencyProfileSchema,
            required: function (this: IUser) {
                return this.role === 'agency';
            },
            // select: false,
            select: function (this: IUser) {
                return this.role === "agent" || this.role === "admin" ? false : true;
            },
        },
        licenses: [
            {
                type: LicenseSchema,
                required: function (this: IUser) {
                    return this.role === 'agency';
                },
                // select: false,
                select: function (this: IUser) {
                    return this.role === "agent" || this.role === "admin" ? false : true;
                },
            },
        ],
        billingInfo: {
            enabled: {
                type: Boolean,
                default: false,
                // select: false,
                select: function (this: IUser) {
                    return this.role === "agent" || this.role === "admin" ? false : true;
                },
            },
        },
        jobsPosted: [
            {
                type: Schema.Types.ObjectId,
                ref: 'Job',
                // select: false,
                select: function (this: IUser) {
                    return this.role === "agent" || this.role === "admin" ? false : true;
                },
            },
        ],
        hiredAgents: [
            {
                type: Schema.Types.ObjectId,
                ref: 'Agent',
                // select: false,
                select: function (this: IUser) {
                    return this.role === "agent" || this.role === "admin" ? false : true;
                },
            },
        ],
        savedAgents: [
            {
                type: Schema.Types.ObjectId,
                ref: 'Agent',
                // select: false,
                select: function (this: IUser) {
                    return this.role === "agent" || this.role === "admin" ? false : true;
                },
            },
        ],
        // -----------------------------------------===========Agent-specific fields===========-----------------------------------
        firstName: {
            type: String,
            required: function (this: IUser) {
                return this.role === 'agent';
            },
            // select: false,
            select: function (this: IUser) {
                return this.role === "agency" || this.role === "admin" ? false : true;
            },
        },
        lastName: {
            type: String,
            required: function (this: IUser) {
                return this.role === 'agent';
            },
            // select: false,
            select: function (this: IUser) {
                return this.role === "agency" || this.role === "admin" ? false : true;
            },
        },
        agentProfile: {
            type: AgentProfileSchema,
            required: function (this: IUser) {
                return this.role === 'agent';
            },
            // select: false,
            select: function (this: IUser) {
                return this.role === "agency" || this.role === "admin" ? false : true;
            },
        },
        paymentInfo: {
            enabled: {
                type: Boolean,
                default: false,
                // select: false,
            },
        },
        appliedJobs: [
            {
                type: Schema.Types.ObjectId,
                ref: 'Job',
                // select: false,
                select: function (this: IUser) {
                    return this.role === "agency" || this.role === "admin" ? false : true;
                },
            },
        ],
        activeJobs: [
            {
                type: Schema.Types.ObjectId,
                ref: 'Job',
                // select: false,
                select: function (this: IUser) {
                    return this.role === "agency" || this.role === "admin" ? false : true;
                },
            },
        ],
        hiredJobs: [
            {
                type: Schema.Types.ObjectId,
                ref: 'Job',
                select: function (this: IUser) {
                    return this.role === "agency" || this.role === "admin" ? false : true;
                },
            },
        ],
        completedJobs: [
            {
                type: Schema.Types.ObjectId,
                ref: 'Job',
                // select: false,
                select: function (this: IUser) {
                    return this.role === "agency" || this.role === "admin" ? false : true;
                },
            },
        ],
        savedJobs: [
            {
                type: Schema.Types.ObjectId,
                ref: 'Job',
                // select: false,
                select: function (this: IUser) {
                    return this.role === "agency" || this.role === "admin" ? false : true;
                },
            },
        ],

        //--------------------OVERALL-------------
        name: { type: String, default: null },
        status: { type: Boolean, default: true },
        soft_delete: { type: Boolean, default: false }
    },
    {
        timestamps: true,
        versionKey: false,
    }
);

// 🔐 Static method to hash a password
UserSchema.statics.generateHash = async function (password: string): Promise<string> {
    const saltRounds = 10;
    return await bcrypt.hash(password, saltRounds);
};

// 🔐 Pre-save middleware to hash password
UserSchema.pre<IUser>('save', async function (next) {
    if (!this.isModified('password')) return next();

    try {
        const saltRounds = 10;
        this.password = await bcrypt.hash(this.password, saltRounds);
        next();
    } catch (err) {
        next(err as Error);
    }
});

UserSchema.pre<IUser>('save', async function (next) {
    try {
        if (this.role === "agency") {
            this.name = this.agencyName ?? ''
        } else if (this.role === "agent") {
            this.name = `${this.firstName} ${this.lastName}`;
        }
        next();
    } catch (err) {
        next(err as Error);
    }
});
// 🔐 Instance method to compare password
UserSchema.methods.comparePassword = async function (candidatePassword: string): Promise<boolean> {
    return await bcrypt.compare(candidatePassword, this.password);
};

export const UserModel = mongoose.model<IUser>('User', UserSchema);