import bcrypt from 'bcryptjs';
import mongoose, { Schema, Document } from 'mongoose';
import { v4 as uuidV4 } from 'uuid'

export interface IUser extends Document {
    _id: string;
    id: string;
    email: string;
    name: string;
    password: string;
    role: 'agency' | 'agent' | 'admin';
    createdAt: Date;
    updatedAt: Date;
    notifications: {
        emailNotifications: boolean;
        smsNotifications: boolean;
    };
    // -------------------------------------------Agency-specific fields---------------------------------------------------
    agencyName?: string;
    agencyType?: string;
    profile?: {
        photo?: string;
        description?: string;
        phone?: string;
        telegramHandle?: string;
        location?: {
            country: string;
            state: string;
            zipcode: string;
            addressLine: string;
        };
    };
    licenses?: { type: string; number: string; expiryDate: Date }[];
    billingInfo?: { enabled: boolean };
    jobsPosted?: mongoose.Types.ObjectId[];
    hiredAgents?: mongoose.Types.ObjectId[];
    savedAgents?: mongoose.Types.ObjectId[];
    //-------------------------------------------- Agent-specific --------------------------------------------------------
    firstName?: string;
    lastName?: string;
    agentProfile?: {
        photo?: string;
        location?: {
            country: string;
            state: string;
            zipcode: string;
            addressLine: string;
        };
        autoGeneratedProfile?: string;
        skills?: { name: string; details: string }[];
        hourlyRate?: number;
        licenses?: { type: string; number: string; expiryDate: Date }[];
        trainingCertificates?: { name: string; date: Date }[];
        taxForm?: string;
        employmentHistory?: { company: string; role: string; startDate: Date; endDate?: Date }[];
        education?: { institution: string; degree: string; startDate: Date; endDate?: Date }[];
        additionalTraining?: { name: string; details: string }[];
        stats?: {
            visibility: 'Public' | 'Private' | 'BlitzOnly';
            projectPreference?: string;
            height?: number;
            weight?: number;
            experienceLevel: 'Beginner' | 'Intermediate' | 'Expert';
            category: string;
            expertise: string[];
        };
        availability?: { status: string; details: string };
        languages?: { name: string; proficiency: 'Basic' | 'Intermediate' | 'Advanced' }[];
        telegramHandle?: string;
    };
    paymentInfo?: { enabled: boolean };
    appliedJobs?: mongoose.Types.ObjectId[];
    activeJobs?: mongoose.Types.ObjectId[];
    hiredJobs?: mongoose.Types.ObjectId[];
    completedJobs?: mongoose.Types.ObjectId[];
    savedJobs?: mongoose.Types.ObjectId[];
}

const UserSchema: Schema = new Schema(
    {
        id: { type: String, required: true, unique: true, default: uuidV4() },
        email: { type: String, required: true, unique: true },
        password: { type: String, required: true, minlength: 8 },
        role: { type: String, enum: ['agency', 'agent', 'admin'], required: true },
        notifications: {
            emailNotifications: { type: Boolean, default: true },
            smsNotifications: { type: Boolean, default: false },
        },
        //-------------------------------------------- Agency-specific fields--------------------------------------------
        agencyName: {
            type: String,
            required: function (this: IUser) {
                return this.role === 'agency';
            },
        },
        agencyType: {
            type: String,
            required: function (this: IUser) {
                return this.role === 'agency';
            },
        },
        profile: {
            photo: { type: String },
            description: { type: String },
            phone: {
                type: String,
                required: function (this: IUser) {
                    return this.role === 'agency';
                },
            },
            telegramHandle: { type: String },
            location: {
                country: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agency';
                    },
                },
                state: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agency';
                    },
                },
                zipcode: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agency';
                    },
                    match: /^[0-9]{5,10}$/,
                },
                addressLine: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agency';
                    },
                },
            },
        },
        licenses: [
            {
                type: { type: String, required: true },
                number: { type: String, required: true },
                expiryDate: { type: Date, required: true },
            },
        ],
        billingInfo: {
            enabled: { type: Boolean, default: false },
        },
        jobsPosted: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
        hiredAgents: [{ type: Schema.Types.ObjectId, ref: 'Agent' }],
        savedAgents: [{ type: Schema.Types.ObjectId, ref: 'Agent' }],
        // ---------------------------------------------Agent-specific fields------------------------------------------
        firstName: {
            type: String,
            required: function (this: IUser) {
                return this.role === 'agent';
            },
        },
        lastName: {
            type: String,
            required: function (this: IUser) {
                return this.role === 'agent';
            },
        },
        agentProfile: {
            photo: { type: String },
            location: {
                country: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agent';
                    },
                },
                state: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agent';
                    },
                },
                zipcode: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agent';
                    },
                    match: /^[0-9]{5,10}$/,
                },
                addressLine: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agent';
                    },
                },
            },
            autoGeneratedProfile: {
                type: String,
                required: function (this: IUser) {
                    return this.role === 'agent';
                },
            },
            skills: [
                {
                    name: { type: String, required: true },
                    details: { type: String },
                },
            ],
            hourlyRate: {
                type: Number,
                required: function (this: IUser) {
                    return this.role === 'agent';
                },
                min: 0,
            },
            licenses: [
                {
                    type: { type: String, required: true },
                    number: { type: String, required: true },
                    expiryDate: { type: Date, required: true },
                },
            ],
            trainingCertificates: [
                {
                    name: { type: String, required: true },
                    date: { type: Date, required: true },
                },
            ],
            taxForm: { type: String },
            employmentHistory: [
                {
                    company: { type: String, required: true },
                    role: { type: String, required: true },
                    startDate: { type: Date, required: true },
                    endDate: { type: Date },
                },
            ],
            education: [
                {
                    institution: { type: String, required: true },
                    degree: { type: String, required: true },
                    startDate: { type: Date, required: true },
                    endDate: { type: Date },
                },
            ],
            additionalTraining: [
                {
                    name: { type: String, required: true },
                    details: { type: String, required: true },
                },
            ],
            stats: {
                visibility: {
                    type: String,
                    enum: ['Public', 'Private', 'BlitzOnly'],
                    required: function (this: IUser) {
                        return this.role === 'agent';
                    },
                },
                projectPreference: { type: String },
                height: { type: Number },
                weight: { type: Number },
                experienceLevel: {
                    type: String,
                    enum: ['Beginner', 'Intermediate', 'Expert'],
                    required: function (this: IUser) {
                        return this.role === 'agent';
                    },
                },
                category: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agent';
                    },
                },
                expertise: {
                    type: [String],
                    validate: [
                        function (val: string[]) {
                            return val.length <= 10;
                        },
                        'Expertise cannot exceed 10 items',
                    ],
                },
            },
            availability: {
                status: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agent';
                    },
                },
                details: {
                    type: String,
                    required: function (this: IUser) {
                        return this.role === 'agent';
                    },
                },
            },
            languages: [
                {
                    name: { type: String, required: true },
                    proficiency: { type: String, enum: ['Basic', 'Intermediate', 'Advanced'], required: true },
                },
            ],
            telegramHandle: { type: String },
        },
        paymentInfo: {
            enabled: { type: Boolean, default: false },
        },
        appliedJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
        activeJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
        hiredJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
        completedJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
        savedJobs: [{ type: Schema.Types.ObjectId, ref: 'Job' }],
    },
    {
        timestamps: true,
        versionKey: false
    }
);

// 🔐 Static method to hash a password
UserSchema.statics.generateHash = async function (password: string): Promise<string> {
    const saltRounds = 10;
    return await bcrypt.hash(password, saltRounds);
};

// 🔐 Pre-save middleware to hash password
UserSchema.pre<IUser>('save', async function (next) {
    // Only hash the password if it's new or modified
    if (!this.isModified('password')) return next();

    try {
        const saltRounds = 10;
        this.password = await bcrypt.hash(this.password, saltRounds);
        next();
    } catch (err) {
        next(err as any);
    }
});

// 🔐 Instance method to compare password
UserSchema.methods.comparePassword = async function (candidatePassword: string): Promise<boolean> {
    return await bcrypt.compare(candidatePassword, this.password);
};

export const UserModel = mongoose.model<IUser>('User', UserSchema);


