import { ObjectId } from 'mongodb';

// Enum for common statuses and types
enum JobVisibility { Public = 'Public', Private = 'Private' }
enum JobType { FullTime = 'FullTime', PartTime = 'PartTime', Contract = 'Contract' }
enum RequirementType { Mandatory = 'Mandatory', Optional = 'Optional' }
enum DressCode { Formal = 'Formal', Casual = 'Casual', Uniform = 'Uniform' }
enum Gender { Male = 'Male', Female = 'Female', Other = 'Other' }
enum ExperienceLevel { Beginner = 'Beginner', Intermediate = 'Intermediate', Expert = 'Expert' }
enum ProfileVisibility { Public = 'Public', Private = 'Private', BlitzOnly = 'BlitzOnly' }
enum LanguageProficiency { Basic = 'Basic', Intermediate = 'Intermediate', Advanced = 'Advanced' }

// Address interface for reuse
interface Address {
  country: string; // Required
  state: string; // Required
  zipcode: string; // Required, format: 5-10 chars
  addressLine: string; // Required
}

// License interface for reuse
interface License {
  type: string; // Required
  number: string; // Required
  expiryDate: Date; // Required
}

// Skill interface for reuse
interface Skill {
  name: string; // Required
  details: string; // Optional
}

// Base User interface
interface User {
  _id: ObjectId;
  email: string; // Required, unique, email format
  password: string; // Required, min 8 chars
  createdAt: Date;
  updatedAt: Date;
  notifications: {
    emailNotifications: boolean; // Default: true
    smsNotifications: boolean; // Default: false
  };
}

// Agency Model
interface Agency extends User {
  agencyName: string; // Required
  agencyType: string; // Required
  profile: {
    photo?: string; // Optional
    description?: string; // Optional
    phone: string; // Required, phone format
    telegramHandle?: string; // Optional
    location: Address; // Required
  };
  licenses: License[]; // Optional
  billingInfo?: {
    // Disabled for now as per document
    enabled: boolean; // Default: false
  };
  jobsPosted: ObjectId[]; // References to Job
  hiredAgents: ObjectId[]; // References to Agent
  savedAgents: ObjectId[]; // References to Agent
}

// Agent Model
interface Agent extends User {
  firstName: string; // Required
  lastName: string; // Required
  profile: {
    photo?: string; // Optional
    location: Address; // Required
    autoGeneratedProfile: string; // Non-editable
    skills: Skill[]; // Optional
    hourlyRate: number; // Required, min 0
    licenses: License[]; // Optional
    trainingCertificates: { name: string; date: Date }[]; // Optional
    taxForm?: string; // Optional
    employmentHistory: { company: string; role: string; startDate: Date; endDate?: Date }[]; // Optional
    education: { institution: string; degree: string; startDate: Date; endDate?: Date }[]; // Optional
    additionalTraining: { name: string; details: string }[]; // Optional
    stats: {
      visibility: ProfileVisibility; // Required
      projectPreference?: string; // Optional
      height?: number; // Optional, in cm
      weight?: number; // Optional, in kg
      experienceLevel: ExperienceLevel; // Required
      category: string; // Required
      expertise: string[]; // Max 10
    };
    availability: { status: string; details: string }; // Required
    languages: { name: string; proficiency: LanguageProficiency }[]; // Optional
    telegramHandle?: string; // Optional
  };
  paymentInfo?: {
    // Disabled for now as per document
    enabled: boolean; // Default: false
  };
  appliedJobs: ObjectId[]; // References to Job
  activeJobs: ObjectId[]; // References to Job
  hiredJobs: ObjectId[]; // References to Job
  completedJobs: ObjectId[]; // References to Job
  savedJobs: ObjectId[]; // References to Job
}

// Admin Model
interface Admin extends User {
  role: 'Admin'; // Fixed value
}

// Job Model
interface Job {
  _id: ObjectId;
  agencyId: ObjectId; // Reference to Agency
  name: string; // Required
  visibility: JobVisibility; // Required
  type: JobType; // Required
  rate: number; // Required, min 0
  numberOfAgents: number; // Required, min 1
  mainCategory: string; // Required
  subCategory: string; // Required
  licenseType: string; // Required
  description: string; // Required
  location: Address; // Required
  requirementType: RequirementType; // Required
  dressCode: DressCode; // Required
  startDate: Date; // Required
  closeDate: Date; // Required
  languageRequirements: {
    englishProficiency: LanguageProficiency; // Required
    additionalLanguages: { name: string; proficiency: LanguageProficiency }[]; // Optional
  };
  gender: Gender; // Required
  payNet: number; // Required, min 0
  status: 'Pending' | 'Approved' | 'Active' | 'Completed'; // Default: Pending
  appliedAgents: ObjectId[]; // References to Agent
  hiredAgents: ObjectId[]; // References to Agent
  createdAt: Date;
  updatedAt: Date;
}

// Message Model for private messaging
interface Message {
  _id: ObjectId;
  senderId: ObjectId; // Reference to User (Agency or Agent)
  receiverId: ObjectId; // Reference to User (Agency or Agent)
  content: string; // Required
  timestamp: Date;
  read: boolean; // Default: false
}

// Notification Model
interface Notification {
  _id: ObjectId;
  userId: ObjectId; // Reference to User (Agency or Agent)
  content: string; // Required
  type: 'JobUpdate' | 'Message' | 'System'; // Required
  read: boolean; // Default: false
  createdAt: Date;
}

// Support Request Model
interface SupportRequest {
  _id: ObjectId;
  userId: ObjectId; // Reference to User (Agency or Agent)
  firstName: string; // Required
  lastName: string; // Required
  email: string; // Required, email format
  message: string; // Required
  status: 'Open' | 'InProgress' | 'Resolved'; // Default: Open
  createdAt: Date;
  updatedAt: Date;
}

// Clock In/Out Model
interface ClockRecord {
  _id: ObjectId;
  agentId: ObjectId; // Reference to Agent
  jobId: ObjectId; // Reference to Job
  clockIn: Date; // Required
  clockOut?: Date; // Optional
  createdAt: Date;
}

// Export all interfaces
export {
  Agency,
  Agent,
  Admin,
  Job,
  Message,
  Notification,
  SupportRequest,
  ClockRecord,
  JobVisibility,
  JobType,
  RequirementType,
  DressCode,
  Gender,
  ExperienceLevel,
  ProfileVisibility,
  LanguageProficiency
};