// import { UserModel } from "../../model/User.model"

// export async function findOneAUth(id: string) {
//     const user = await UserModel.findById(id);
//     return user;
// }


import { Request } from "express";
import { paginationData } from "../../core/helper/helper.service";
import { IAgencyProfile, IAgentProfile, IUser, UserModel } from "../../model/User.model";

export class ProfileService {

    async findOneAUth(id: string) {
        const user = await UserModel.findById(id);
        return user;
    }

    // Get user profile
    async getProfile(userId: string, role: 'agency' | 'agent' | 'admin'): Promise<IUser> {
        const user = await UserModel.findById(userId);
        if (!user) {
            throw new Error('User not found');
        }
        if (user.role !== role) {
            throw new Error('Role mismatch');
        }
        return user;
    }

    // Update user profile (role-specific)
    async updateProfile(userId: string, role: 'agency' | 'agent' | 'admin', updates: Partial<IUser>): Promise<IUser> {
        const user = await UserModel.findById(userId);
        if (!user) {
            throw new Error('User not found');
        }
        if (user.role !== role) {
            throw new Error('Role mismatch');
        }

        // Role-specific validation and updates
        if (role === 'agency') {
            // Update Agency-specific fields
            if (updates.agencyName) user.agencyName = updates.agencyName;
            if (updates.agencyType) user.agencyType = updates.agencyType;
            if (updates.profile) {
                user.profile = { ...user.profile, ...updates.profile } as IAgencyProfile;
                // Validate required fields for agency
                if (!user.profile?.phone || !user.profile?.location) {
                    throw new Error('Phone and location are required for agency profile');
                }
            }
            if (updates.licenses) user.licenses = updates.licenses;
            if (updates.billingInfo) user.billingInfo = updates.billingInfo;
        } else if (role === 'agent') {
            // Update Agent-specific fields
            if (updates.firstName) user.firstName = updates.firstName;
            if (updates.lastName) user.lastName = updates.lastName;
            if (updates.agentProfile) {
                user.agentProfile = { ...user.agentProfile, ...updates.agentProfile } as IAgentProfile;
                // Validate required fields for agent
                if (
                    !user.agentProfile?.location ||
                    !user.agentProfile?.autoGeneratedProfile ||
                    !user.agentProfile?.hourlyRate ||
                    !user.agentProfile?.stats?.visibility ||
                    !user.agentProfile?.stats?.experienceLevel ||
                    !user.agentProfile?.stats?.category ||
                    !user.agentProfile?.availability
                ) {
                    throw new Error('Required agent profile fields are missing');
                }
            }
            if (updates.paymentInfo) user.paymentInfo = updates.paymentInfo;
        } else if (role === 'admin') {
            // Admin profile updates (minimal for now)
            if (updates.email) user.email = updates.email;
        }

        // Update common fields
        if (updates.notifications) user.notifications = updates.notifications;

        await user.save();
        return user;
    }

    async getAllUsers(req: Request) {
        const aggregatePipeline: any = [];
        const { data, page_data } = await paginationData(req, UserModel, aggregatePipeline, [], []);
        return { data, page_data };
    }

    async getAllAgents(req: Request) {
        const aggregatePipeline: any = [
            {
                $match: {
                    role: "agent"
                }
            }
        ];
        const { data, page_data } = await paginationData(req, UserModel, aggregatePipeline, [], []);
        return { data, page_data };
    }

    async getAllAgency(req: Request) {
        const aggregatePipeline: any = [
            {
                $match: {
                    role: "agency"
                }
            }
        ];
        const { data, page_data } = await paginationData(req, UserModel, aggregatePipeline, [], []);
        return { data, page_data };
    }
}